# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSE9IlWZdWvOqBnIGwvJq05ReugobYGO
"""

INPUT=input()
score=INPUT.split()
fail=0
for i in range(len(score)):
  if int(score[i])<60:
        fail+=1
print(fail)