# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hKcopQ5z-8_6zTzkcQTpcRjvt2mfeiWk
"""

INPUT=input()
score=INPUT.split()
fail=0
max=0
min=100
for i in range(len(score)):
  if int(score[i])<min:
    min=int(score[i])
  if int(score[i])>max:
    max=int(score[i])
  if int(score[i])<60:
        fail+=1
print('Fail= ',fail,',Max= ',max,',Min= ',min)
score = input().split()

fail = 0
sum = 0

for i in score:
  if int(i)<60:
    fail = fail+1
    sum = sum + int(i)

print(fail)
print(sum/fail)
