# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hKcopQ5z-8_6zTzkcQTpcRjvt2mfeiWk
"""

score = input().split()

fail = 0
sum = 0

for i in score:
  if int(i)<60:
    fail = fail+1
    sum = sum + int(i)

print(fail)
print(sum/fail)